### PR TITLE
Translation to pt-br

### PR DESCRIPTION
**Pull request by dev-araujo**
I had access to the solidity-style-guide in a solidity study group, in the web3dev community on [discord](https://discord.com/invite/UXDUzG2hhE) . And I believe it could be useful for the Brazilian dev audience to have a version of the doc in Portuguese

### CODE REVIEW

**Comment by wilsoncusack** [comment]
Amazing, thanks!

**Review by biasgooseRX — COMMENTED** [review]
It looks really good to me. Thank you. Only question I have is Solitações de pull could maybe just be written "PR" or "Pull Requests"? very minor but I am unsure on this one since I have seen mostly Portuguese speaking devs call it Pull Request without translation.

**Comment by dev-araujo** [comment]
@biasgooseRX 
Yes, you are correct. It's common for us to use 'PR' or 'Pull Requests', keeping the original term, but in Brazil, it's also common to use certain 'adaptations' that are not so grammatically correct, such as 'solicitações de pull', 'commitar' (an adaptation for the act of making commits), and things like that. 
However, I believe that due to the more formal nature, I can change 'solicitações de pull' to 'Pull Requests'.

**Review by biasgooseRX — APPROVED** [review]
Thanks @dev-araujo! Great work, it all looks perfect to me now

**Comment by cb-heimdall** [comment]
Review Error for biasgooseRX @ 2024-04-24 18:09:17 UTC
User must have write permissions to review

**Review by wilsoncusack — APPROVED** [review]

**Pull request merged**
